// GENERATED FILE. Edit assets/category_catalog/category_catalog.json instead.
import 'package:vector_graphics/vector_graphics.dart';

class CategoryIconToken {
  const CategoryIconToken({
    required this.id,
    required this.sourceAssetPath,
    required this.compiledAssetPath,
    required this.bytesLoader,
    required this.logBoxSourceAssetPath,
    required this.logBoxCompiledAssetPath,
    required this.logBoxBytesLoader,
    required this.semanticName,
  });

  final String id;
  final String sourceAssetPath;
  final String compiledAssetPath;
  final AssetBytesLoader bytesLoader;
  final String logBoxSourceAssetPath;
  final String logBoxCompiledAssetPath;
  final AssetBytesLoader logBoxBytesLoader;
  final String semanticName;
}

abstract final class CategoryIconCatalog {
  static const CategoryIconToken fallback = CategoryIconToken(
    id: 'fallback',
    sourceAssetPath: 'assets/category_icons/shirt.svg',
    compiledAssetPath: 'assets/category_icons/shirt.svg.vec',
    bytesLoader: AssetBytesLoader('assets/category_icons/shirt.svg.vec'),
    logBoxSourceAssetPath: 'assets/logbox_category_icons/shirt.svg',
    logBoxCompiledAssetPath: 'assets/logbox_category_icons/shirt.svg.vec',
    logBoxBytesLoader: AssetBytesLoader('assets/logbox_category_icons/shirt.svg.vec'),
    semanticName: 'category icon fallback',
  );

  static const Map<String, CategoryIconToken> values =
      <String, CategoryIconToken>{
    "icon_01": CategoryIconToken(
      id: "icon_01",
      sourceAssetPath: "assets/category_icons/shirt.svg",
      compiledAssetPath: "assets/category_icons/shirt.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/shirt.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/shirt.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/shirt.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/shirt.svg.vec"),
      semanticName: "shirt",
    ),
    "icon_02": CategoryIconToken(
      id: "icon_02",
      sourceAssetPath: "assets/category_icons/shopping-cart.svg",
      compiledAssetPath: "assets/category_icons/shopping-cart.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/shopping-cart.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/shopping-cart.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/shopping-cart.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/shopping-cart.svg.vec"),
      semanticName: "shopping cart",
    ),
    "icon_03": CategoryIconToken(
      id: "icon_03",
      sourceAssetPath: "assets/category_icons/handbag.svg",
      compiledAssetPath: "assets/category_icons/handbag.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/handbag.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/handbag.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/handbag.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/handbag.svg.vec"),
      semanticName: "handbag",
    ),
    "icon_04": CategoryIconToken(
      id: "icon_04",
      sourceAssetPath: "assets/category_icons/ambulance.svg",
      compiledAssetPath: "assets/category_icons/ambulance.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/ambulance.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/ambulance.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/ambulance.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/ambulance.svg.vec"),
      semanticName: "ambulance",
    ),
    "icon_05": CategoryIconToken(
      id: "icon_05",
      sourceAssetPath: "assets/category_icons/beer.svg",
      compiledAssetPath: "assets/category_icons/beer.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/beer.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/beer.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/beer.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/beer.svg.vec"),
      semanticName: "beer",
    ),
    "icon_06": CategoryIconToken(
      id: "icon_06",
      sourceAssetPath: "assets/category_icons/briefcase-business.svg",
      compiledAssetPath: "assets/category_icons/briefcase-business.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/briefcase-business.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/briefcase-business.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/briefcase-business.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/briefcase-business.svg.vec"),
      semanticName: "briefcase",
    ),
    "icon_07": CategoryIconToken(
      id: "icon_07",
      sourceAssetPath: "assets/category_icons/bitcoin.svg",
      compiledAssetPath: "assets/category_icons/bitcoin.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/bitcoin.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/bitcoin.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/bitcoin.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/bitcoin.svg.vec"),
      semanticName: "bitcoin",
    ),
    "icon_08": CategoryIconToken(
      id: "icon_08",
      sourceAssetPath: "assets/category_icons/broccoli.svg",
      compiledAssetPath: "assets/category_icons/broccoli.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/broccoli.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/broccoli.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/broccoli.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/broccoli.svg.vec"),
      semanticName: "broccoli",
    ),
    "icon_09": CategoryIconToken(
      id: "icon_09",
      sourceAssetPath: "assets/category_icons/bus-front.svg",
      compiledAssetPath: "assets/category_icons/bus-front.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/bus-front.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/bus-front.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/bus-front.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/bus-front.svg.vec"),
      semanticName: "bus",
    ),
    "icon_10": CategoryIconToken(
      id: "icon_10",
      sourceAssetPath: "assets/category_icons/factory.svg",
      compiledAssetPath: "assets/category_icons/factory.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/factory.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/factory.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/factory.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/factory.svg.vec"),
      semanticName: "factory",
    ),
    "icon_11": CategoryIconToken(
      id: "icon_11",
      sourceAssetPath: "assets/category_icons/plane.svg",
      compiledAssetPath: "assets/category_icons/plane.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/plane.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/plane.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/plane.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/plane.svg.vec"),
      semanticName: "plane",
    ),
    "icon_12": CategoryIconToken(
      id: "icon_12",
      sourceAssetPath: "assets/category_icons/car-taxi-front.svg",
      compiledAssetPath: "assets/category_icons/car-taxi-front.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/car-taxi-front.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/car-taxi-front.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/car-taxi-front.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/car-taxi-front.svg.vec"),
      semanticName: "car",
    ),
    "icon_13": CategoryIconToken(
      id: "icon_13",
      sourceAssetPath: "assets/category_icons/fuel.svg",
      compiledAssetPath: "assets/category_icons/fuel.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/fuel.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/fuel.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/fuel.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/fuel.svg.vec"),
      semanticName: "fuel",
    ),
    "icon_14": CategoryIconToken(
      id: "icon_14",
      sourceAssetPath: "assets/category_icons/paw-print.svg",
      compiledAssetPath: "assets/category_icons/paw-print.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/paw-print.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/paw-print.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/paw-print.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/paw-print.svg.vec"),
      semanticName: "paw print",
    ),
    "icon_15": CategoryIconToken(
      id: "icon_15",
      sourceAssetPath: "assets/category_icons/hamburger.svg",
      compiledAssetPath: "assets/category_icons/hamburger.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/hamburger.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/hamburger.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/hamburger.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/hamburger.svg.vec"),
      semanticName: "hamburger",
    ),
    "icon_16": CategoryIconToken(
      id: "icon_16",
      sourceAssetPath: "assets/category_icons/lightbulb.svg",
      compiledAssetPath: "assets/category_icons/lightbulb.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/lightbulb.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/lightbulb.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/lightbulb.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/lightbulb.svg.vec"),
      semanticName: "light bulb",
    ),
    "icon_17": CategoryIconToken(
      id: "icon_17",
      sourceAssetPath: "assets/category_icons/dollar-sign.svg",
      compiledAssetPath: "assets/category_icons/dollar-sign.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/dollar-sign.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/dollar-sign.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/dollar-sign.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/dollar-sign.svg.vec"),
      semanticName: "dollar",
    ),
    "icon_18": CategoryIconToken(
      id: "icon_18",
      sourceAssetPath: "assets/category_icons/hospital.svg",
      compiledAssetPath: "assets/category_icons/hospital.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/hospital.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/hospital.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/hospital.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/hospital.svg.vec"),
      semanticName: "hospital",
    ),
    "icon_19": CategoryIconToken(
      id: "icon_19",
      sourceAssetPath: "assets/category_icons/piggy-bank.svg",
      compiledAssetPath: "assets/category_icons/piggy-bank.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/piggy-bank.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/piggy-bank.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/piggy-bank.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/piggy-bank.svg.vec"),
      semanticName: "piggy bank",
    ),
    "icon_20": CategoryIconToken(
      id: "icon_20",
      sourceAssetPath: "assets/category_icons/clover.svg",
      compiledAssetPath: "assets/category_icons/clover.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/clover.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/clover.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/clover.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/clover.svg.vec"),
      semanticName: "clover",
    ),
    "icon_21": CategoryIconToken(
      id: "icon_21",
      sourceAssetPath: "assets/category_icons/drama.svg",
      compiledAssetPath: "assets/category_icons/drama.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/drama.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/drama.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/drama.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/drama.svg.vec"),
      semanticName: "drama",
    ),
    "icon_22": CategoryIconToken(
      id: "icon_22",
      sourceAssetPath: "assets/category_icons/gamepad-2.svg",
      compiledAssetPath: "assets/category_icons/gamepad-2.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/gamepad-2.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/gamepad-2.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/gamepad-2.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/gamepad-2.svg.vec"),
      semanticName: "gamepad",
    ),
    "icon_23": CategoryIconToken(
      id: "icon_23",
      sourceAssetPath: "assets/category_icons/cross.svg",
      compiledAssetPath: "assets/category_icons/cross.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/cross.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/cross.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/cross.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/cross.svg.vec"),
      semanticName: "cross",
    ),
    "icon_24": CategoryIconToken(
      id: "icon_24",
      sourceAssetPath: "assets/category_icons/dumbbell.svg",
      compiledAssetPath: "assets/category_icons/dumbbell.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/dumbbell.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/dumbbell.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/dumbbell.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/dumbbell.svg.vec"),
      semanticName: "dumbbell",
    ),
    "icon_25": CategoryIconToken(
      id: "icon_25",
      sourceAssetPath: "assets/category_icons/clapperboard.svg",
      compiledAssetPath: "assets/category_icons/clapperboard.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/clapperboard.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/clapperboard.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/clapperboard.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/clapperboard.svg.vec"),
      semanticName: "clapperboard",
    ),
    "icon_26": CategoryIconToken(
      id: "icon_26",
      sourceAssetPath: "assets/category_icons/gift.svg",
      compiledAssetPath: "assets/category_icons/gift.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/gift.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/gift.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/gift.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/gift.svg.vec"),
      semanticName: "gift",
    ),
    "icon_27": CategoryIconToken(
      id: "icon_27",
      sourceAssetPath: "assets/category_icons/house.svg",
      compiledAssetPath: "assets/category_icons/house.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/house.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/house.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/house.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/house.svg.vec"),
      semanticName: "house",
    ),
    "icon_28": CategoryIconToken(
      id: "icon_28",
      sourceAssetPath: "assets/category_icons/ghost.svg",
      compiledAssetPath: "assets/category_icons/ghost.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/ghost.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/ghost.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/ghost.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/ghost.svg.vec"),
      semanticName: "ghost",
    ),
    "icon_29": CategoryIconToken(
      id: "icon_29",
      sourceAssetPath: "assets/category_icons/heart.svg",
      compiledAssetPath: "assets/category_icons/heart.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/heart.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/heart.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/heart.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/heart.svg.vec"),
      semanticName: "heart",
    ),
    "icon_30": CategoryIconToken(
      id: "icon_30",
      sourceAssetPath: "assets/category_icons/music-4.svg",
      compiledAssetPath: "assets/category_icons/music-4.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/music-4.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/music-4.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/music-4.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/music-4.svg.vec"),
      semanticName: "music",
    ),
    "icon_31": CategoryIconToken(
      id: "icon_31",
      sourceAssetPath: "assets/category_icons/graduation-cap.svg",
      compiledAssetPath: "assets/category_icons/graduation-cap.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/graduation-cap.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/graduation-cap.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/graduation-cap.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/graduation-cap.svg.vec"),
      semanticName: "graduation cap",
    ),
    "icon_32": CategoryIconToken(
      id: "icon_32",
      sourceAssetPath: "assets/category_icons/baby.svg",
      compiledAssetPath: "assets/category_icons/baby.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/baby.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/baby.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/baby.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/baby.svg.vec"),
      semanticName: "baby",
    ),
    "icon_33": CategoryIconToken(
      id: "icon_33",
      sourceAssetPath: "assets/category_icons/hand-metal.svg",
      compiledAssetPath: "assets/category_icons/hand-metal.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/hand-metal.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/hand-metal.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/hand-metal.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/hand-metal.svg.vec"),
      semanticName: "hand",
    ),
    "icon_34": CategoryIconToken(
      id: "icon_34",
      sourceAssetPath: "assets/category_icons/coffee.svg",
      compiledAssetPath: "assets/category_icons/coffee.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/coffee.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/coffee.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/coffee.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/coffee.svg.vec"),
      semanticName: "coffee",
    ),
    "icon_35": CategoryIconToken(
      id: "icon_35",
      sourceAssetPath: "assets/category_icons/utensils.svg",
      compiledAssetPath: "assets/category_icons/utensils.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/utensils.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/utensils.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/utensils.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/utensils.svg.vec"),
      semanticName: "utensils",
    ),
    "icon_36": CategoryIconToken(
      id: "icon_36",
      sourceAssetPath: "assets/category_icons/wine.svg",
      compiledAssetPath: "assets/category_icons/wine.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/wine.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/wine.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/wine.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/wine.svg.vec"),
      semanticName: "wine",
    ),
    "icon_37": CategoryIconToken(
      id: "icon_37",
      sourceAssetPath: "assets/category_icons/apple.svg",
      compiledAssetPath: "assets/category_icons/apple.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/apple.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/apple.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/apple.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/apple.svg.vec"),
      semanticName: "apple",
    ),
    "icon_38": CategoryIconToken(
      id: "icon_38",
      sourceAssetPath: "assets/category_icons/luggage.svg",
      compiledAssetPath: "assets/category_icons/luggage.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/luggage.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/luggage.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/luggage.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/luggage.svg.vec"),
      semanticName: "luggage",
    ),
    "icon_39": CategoryIconToken(
      id: "icon_39",
      sourceAssetPath: "assets/category_icons/parasol.svg",
      compiledAssetPath: "assets/category_icons/parasol.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/parasol.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/parasol.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/parasol.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/parasol.svg.vec"),
      semanticName: "parasol",
    ),
    "icon_40": CategoryIconToken(
      id: "icon_40",
      sourceAssetPath: "assets/category_icons/palette.svg",
      compiledAssetPath: "assets/category_icons/palette.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/palette.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/palette.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/palette.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/palette.svg.vec"),
      semanticName: "palette",
    ),
    "icon_41": CategoryIconToken(
      id: "icon_41",
      sourceAssetPath: "assets/category_icons/wrench.svg",
      compiledAssetPath: "assets/category_icons/wrench.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/wrench.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/wrench.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/wrench.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/wrench.svg.vec"),
      semanticName: "wrench",
    ),
    "icon_42": CategoryIconToken(
      id: "icon_42",
      sourceAssetPath: "assets/category_icons/book-open-text.svg",
      compiledAssetPath: "assets/category_icons/book-open-text.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/book-open-text.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/book-open-text.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/book-open-text.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/book-open-text.svg.vec"),
      semanticName: "book",
    ),
    "icon_43": CategoryIconToken(
      id: "icon_43",
      sourceAssetPath: "assets/category_icons/store.svg",
      compiledAssetPath: "assets/category_icons/store.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/store.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/store.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/store.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/store.svg.vec"),
      semanticName: "store",
    ),
    "icon_44": CategoryIconToken(
      id: "icon_44",
      sourceAssetPath: "assets/category_icons/wand-sparkles.svg",
      compiledAssetPath: "assets/category_icons/wand-sparkles.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/wand-sparkles.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/wand-sparkles.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/wand-sparkles.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/wand-sparkles.svg.vec"),
      semanticName: "wand",
    ),
    "icon_45": CategoryIconToken(
      id: "icon_45",
      sourceAssetPath: "assets/category_icons/gem.svg",
      compiledAssetPath: "assets/category_icons/gem.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/gem.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/gem.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/gem.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/gem.svg.vec"),
      semanticName: "gem",
    ),
    "icon_46": CategoryIconToken(
      id: "icon_46",
      sourceAssetPath: "assets/category_icons/plug-2.svg",
      compiledAssetPath: "assets/category_icons/plug-2.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/plug-2.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/plug-2.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/plug-2.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/plug-2.svg.vec"),
      semanticName: "plug",
    ),
    "icon_47": CategoryIconToken(
      id: "icon_47",
      sourceAssetPath: "assets/category_icons/chart-candlestick.svg",
      compiledAssetPath: "assets/category_icons/chart-candlestick.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/chart-candlestick.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/chart-candlestick.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/chart-candlestick.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/chart-candlestick.svg.vec"),
      semanticName: "chart",
    ),
    "icon_48": CategoryIconToken(
      id: "icon_48",
      sourceAssetPath: "assets/category_icons/tent.svg",
      compiledAssetPath: "assets/category_icons/tent.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/tent.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/tent.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/tent.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/tent.svg.vec"),
      semanticName: "tent",
    ),
    "icon_49": CategoryIconToken(
      id: "icon_49",
      sourceAssetPath: "assets/category_icons/crown.svg",
      compiledAssetPath: "assets/category_icons/crown.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/crown.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/crown.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/crown.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/crown.svg.vec"),
      semanticName: "crown",
    ),
    "icon_50": CategoryIconToken(
      id: "icon_50",
      sourceAssetPath: "assets/category_icons/zap.svg",
      compiledAssetPath: "assets/category_icons/zap.svg.vec",
      bytesLoader: AssetBytesLoader("assets/category_icons/zap.svg.vec"),
      logBoxSourceAssetPath: "assets/logbox_category_icons/zap.svg",
      logBoxCompiledAssetPath: "assets/logbox_category_icons/zap.svg.vec",
      logBoxBytesLoader: AssetBytesLoader("assets/logbox_category_icons/zap.svg.vec"),
      semanticName: "zap",
    ),
  };

  static CategoryIconToken resolve(String iconId) => values[iconId] ?? fallback;

  static final Map<String, int> _handles = <String, int>{
    for (final (index, id) in values.keys.indexed) id: index + 1,
  };

  static int handleOf(String iconId) => _handles[iconId] ?? 0;

  static final List<CategoryIconToken> _byHandle =
      List<CategoryIconToken>.unmodifiable(<CategoryIconToken>[
    fallback,
    ...values.values,
  ]);

  static CategoryIconToken tokenForHandle(int handle) => _byHandle[handle];

  static List<CategoryIconToken> get allWithFallback => _byHandle;

  static bool contains(String iconId) => values.containsKey(iconId);

  static List<CategoryIconToken> get all =>
      List<CategoryIconToken>.unmodifiable(values.values);
}
