import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:fluvi/features/dashboard/presentation/core_modes/dashboard_header_visual_engine.dart';

/// The expected equations are deliberately recorded independently of the
/// production helper names. They are the identifying portions of the
/// 69d109c1e1f53ab4c0d2b66f5c576577de3e99c9 fragment runtime, not values
/// generated by the current implementation.
void main() {
  group('classic Header reference lane', () {
    test(
      'RED restores the eight historical shader IDs without an ABI revert',
      () {
        final ids = DashboardHeaderEffectCatalog.effects
            .map((effect) => effect.shaderId)
            .toList(growable: false);

        expect(ids, containsAll(<int>[0, 1, 2, 3, 4, 5, 6, 7, 8]));
        expect(DashboardHeaderEffectCatalog.effects.length, 14);
      },
    );

    test(
      'RED isolates exact 69d109 classic motion equations from palette infrastructure',
      () async {
        final shader = await File(
          'shaders/dashboard_header_field.frag',
        ).readAsString();

        final classicStart = shader.indexOf('vec3 classicReferenceField(');
        final flowStart = shader.indexOf('vec2 fullFieldInverseFlowMap(');
        expect(classicStart, greaterThanOrEqualTo(0));
        expect(flowStart, greaterThan(classicStart));
        final classic = shader.substring(classicStart, flowStart);

        // Historical 69d109 signatures for tide, membrane, lens, cells,
        // balance variants and Deep Drift's former coordinate transport.
        for (final signature in <String>[
          'float field = p.x + ratio + broad * .20 + fine * .12;',
          'field += warp + (bMass - aMass) * mainValue(24) * .46;',
          'field = .5 + (p.x - boundary);',
          'float pressure = (lens * mainValue(24) + satellite * mainValue(27)) * mainValue(25);',
          'pressureSum / count * mainValue(29)',
          'float mapped = p.x <= boundary ?',
          'float seam = exp(-abs(p.x - boundary)',
          'classicTransportPaletteCoordinate(',
        ]) {
          expect(classic, contains(signature));
        }
        expect(classic, contains('sampleCanonicalPalette('));
        expect(shader, contains('canonicalActiveStopCount()'));
        expect(shader, isNot(contains('uniform vec4 uColorA')));
        expect(shader, isNot(contains('uniform vec4 uColorB')));
      },
    );

    test(
      'RED catalog expresses family ownership instead of shader-ID inference',
      () async {
        final engine = await File(
          'lib/features/dashboard/presentation/core_modes/dashboard_header_visual_engine.dart',
        ).readAsString();
        expect(engine, contains('enum DashboardHeaderAnimationFamily'));
        expect(engine, contains('classicReference'));
        expect(engine, contains('fullFieldFlow'));
        expect(engine, contains('required this.family'));
        expect(engine, contains('void selectAnimationFamily('));
      },
    );
  });
}
